Create verticalLine.lua
MCJack123/PrimeUI pull request #13
Opened 2024-09-06 21:44 UTC by ascpial

Just a question about copyright holder, I obviously accept that my contribution is licensed with the CC0 and accept that my contribution is given to the public domain, but do I need to add my name in the license header in the `utils.lua` file?

2024-09-08 17:18 UTC, hooded-person commented
nice

2024-09-09 03:38 UTC, MCJack123 requested changes
Looks alright, just needs a few style fixes before merging.

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +    win.setTextColor(side=="left" and fgColor or bgColor)
Please adjust the spacing and indentation to match the style of the rest of the code.

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +      win.write(("\x95"))
There's an extra set of parentheses that should be removed.

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +---@param side "right"|"left"|nil THe side of the line, either right or left (defaults to left)
Could you make this a boolean instead? There's only two possibilities, so using a string is a bit overcomplicated.

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +---@param x number The X position of the left side of the line
```suggestion
---@param x number The X position of the line
```

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +---@param y number The Y position of the line
```suggestion
---@param y number The Y position of the top of the line
```

2024-09-09 03:38 UTC, MCJack123 commented on verticalLine.lua
> +---@param height number The width/length of the line
```suggestion
---@param height number The height of the line
```

2024-09-09 07:33 UTC, hooded-person commented
Maybe also updated the singular releases file, it is currently already missing the monitor support and the whole clickArea item

2024-09-11 21:30 UTC, MCJack123 approved these changes
Made a few minor changes and a syntax fix, now it LGTM :+1:

2024-09-11 21:31 UTC, merged